<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [2]:
greeting("Super Man")

'Hello Super Man!'

In [3]:
greeting(name="Super Man")

'Hello Super Man!'

In [5]:
greet=greeting(name='Super Man')
print(greet)
print(greeting(name='Super Man'))

Hello Super Man!
Hello Super Man!


In [6]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [8]:
basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

### 1.2 Named functions that don’t return

In [15]:
def greeting(name):
    if name == 'Batman':
        print("test1")
        return 'Hello Batman! So, nice to meet you!'
    else:
        print("test2")
        return f'Hello {name}!'
greeting("Super Man")

test2


'Hello Super Man!'

In [16]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
        print("test1")
    else:
        return f'Hello {name}!'
        print("test2")
greeting("Super Man")

'Hello Super Man!'

### 1.3 Anonymous functions

In [17]:
my_short_function = lambda name: f"Hello {name}!"

In [18]:
my_short_function(name="Super Man")

'Hello Super Man!'

In [46]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19],
         [4, 2, 2],
         [3, 4, 6]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 4, 6],
 [3, 6, 16],
 [4, 2, 2],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [21]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [32]:
sorted(numbers, key = sum)     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [47]:
sorted(numbers, key=lambda x: x[0]**2 *x[1] - x[2])   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[0, 9, 19],
 [9, 0, 10],
 [1, 8, 18],
 [2, 7, 17],
 [4, 2, 2],
 [3, 4, 6],
 [3, 6, 16],
 [8, 1, 11],
 [4, 5, 15],
 [7, 2, 12],
 [5, 4, 14],
 [6, 3, 13]]

In [48]:
id(3**2 * 4 - 6)

1851462583440

In [49]:
id(4**2 * 2 - 2)

1851462583440

### 1.4 Optional arguments

In [36]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [37]:
greeting()

'Hello no one!'

In [40]:
?print
# Docstring:
# print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

# Prints the values to a stream, or to sys.stdout by default.
# Optional keyword arguments:
# file:  a file-like object (stream); defaults to the current sys.stdout.
# sep:   string inserted between values, default a space.
# end:   string appended after the last value, default a newline.
# flush: whether to forcibly flush the stream.
# Type:      builtin_function_or_method

In [41]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?

In [43]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

if the if statement is not satisfied and there is no elif or else, the conditional code is terminated and we go out of the 'loop', returning the result of the bigger def function.

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting("Batman")

'Hello Batman! So, nice to meet you!'

## Exercise 2 :  Calculator functions

In [2]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    if y == 0:
        exit()
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [2]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    if (y==0).any():
        exit()
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [13]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    if y.any == 0:
        exit()
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

print(add(x,y))
print(subtract(x,y))
print(multiply(x,y))
print(divide(x,y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


In [14]:
str(divide(x, y))

'[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]'

In [15]:
add(x,y)

array([100, 100, 100, 100, 100])

In [16]:
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [17]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [18]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [2]:
import numpy as np
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return str(np.max(numbers)) + " at " + str(np.argmax(numbers))
max_info(numbers)

'83 at 2'

In [5]:
import numpy as np
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers):
    return f"{np.max(numbers)} at {np.argmax(numbers)}"
max_info(numbers)

'83 at 2'