<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [7]:
x = 2
print(x+1)
assert x >= 0, "x is becoming negative!"
print(x)

x = -3
print(x)
assert x >= 0, "x is becoming negative!"
print(x+1)

3
2
-3


AssertionError: x is becoming negative!

### 1.2 try-except

In [21]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.4
The square of 4 is 16!


In [22]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.6
The square of 6 is 36!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [15]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

In [20]:
print(funny_add(1, 2))           # Two positional, 1 default
#> 121
print(funny_add(1, 2, 3))        # Three positional
#> 321
print(funny_add(a=1, b=2))       # Two keyword, 1 default
#> 121
print(funny_add(c=3, b=1, a=2))  # Three keyword
#> 312
print(funny_add(1, c=3, b=2))    # One positional, 2 keyword
#> 321
print(funny_add(1, b=2))         # One positional, 1 keyword, 1 default
#> 121

121
321
121
312
321
121


In [23]:
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional

SyntaxError: positional argument follows keyword argument (25483117.py, line 1)

### 2.2 Docstrings

In [24]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

In [25]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [26]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

-1.0

### 2.4 More unpacking

In [27]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [28]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [29]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [31]:
*x, y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

[1, 2, 3] 4 5


In [32]:
x, *y, *z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

SyntaxError: multiple starred expressions in assignment (4060246930.py, line 1)

In [30]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


In [33]:
x, _, y = [1, 2, 3, 4, 5]
print(x, y)

ValueError: too many values to unpack (expected 3)

In [34]:
x, _, *y = [1, 2, 3, 4, 5]
print(x, y)

1 [3, 4, 5]


In [35]:
x, *y = [1, 2, 3, 4, 5]
print(x, y)

1 [2, 3, 4, 5]


## Exercise 1 :  A better calculator I

In [12]:
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    assert (y!=0).any(), 'y is negative'
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [47]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

assert len(x) == len(y), 'x and y are different sizes!'
assert (type(y[0]) == np.int32 or type(y[0]) == np.float64), 'wrong input for y!'
assert (type(x[0]) == np.int32 or type(x[0]) == np.float64), 'wrong input for x!'

def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    assert (y!=0).any(), 'division by 0 error'
    return x/y

add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 2 :  A better calculator II

In [26]:
try:
    def add(x,y):
        return x+y
    def subtract(x,y):
        return x-y
    def multiply(x,y):
        return x*y
    def divide(x,y):
        return x/y
except:
    print('Error: Division by 0')             # This thing does not work, need to put try and except under the definition
    

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [51]:
np.seterr(all = 'raise')

def add(x,y):                      # How to add try and except for all without typing one by one hahaha
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def divide(x,y):
    try:
        return x/y
    except:
        print('Error: Division by 0')

    

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])


add(x,y)
subtract(x,y)
multiply(x,y)
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])