<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

In [ ]:
# import numpy as np

### 1.1 Let’s compare

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [1]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [9]:

print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.
print(py_super_names[-1])   # Reverse indexing


Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


In [66]:
print(np_super_names[2])

Doctor Strange


### 1.3 Accessing data from a dictionary

In [11]:

print(superhero_info["Natasha Romanoff"])
print(superhero_info["Black Widow"])           #error cus "Black Widow" is the value not the key


Black Widow


KeyError: 'Black Widow'

In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [18]:

py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info[0])


['Natasha Romanoff', 'Black Widow']


## 2 Lists vs. Arrays

### 2.1 Size

In [19]:

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array


In [20]:
len(py_list_2d)

10

In [21]:
len(np_array_2d)

10

In [22]:
np_array_2d.shape

(10, 2)

In [25]:
py_list_2d.shape
# Notice the absence of brackets ( ) in shape above. 
# This is because shape is not a function. Instead, 
# it is a property or attribute of the NumPy array.

AttributeError: 'list' object has no attribute 'shape'

### 2.2 Arrays are fussy about type

In [26]:

py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [28]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [29]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [30]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [31]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [32]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [34]:
np_array_3 = np.array([1, 2, 3, 4, 5, 6])
np_array_4 = np.array([10, 20, 30, 40])
np_array_3 + np_array_4

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

### 2.5 Multiplying by a Number

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [36]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [39]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [40]:

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [41]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [43]:

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [51]:
py_list == 3     # Works, but what IS the question?
                 # The question is 'is py_list == 3?'

False

In [46]:
np_array == 3  

array([False, False,  True, False, False])

In [52]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [53]:

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         


In [54]:
sum(py_list)     # sum() is a base Python function

15

In [55]:
max(py_list)     # max() is a base Python function

5

In [56]:
min(py_list)     # min() is a base Python function

1

In [57]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [62]:
mean(py_list)

NameError: name 'mean' is not defined

In [59]:
np_array.sum()

15

In [61]:
sum(np.array) #does not work

TypeError: 'builtin_function_or_method' object is not iterable

In [63]:
np_array.mean()

3.0

In [64]:
np_array.max()

5

In [65]:
np_array.min()

1

(roughly speaking) an operation on a list works on the whole list. In contrast, an operation on an array works on the individual elements of the array.

## Exercise 1 :  Total recall?

1. - Lists and Arrays store 1 type of data only. To store 2 types of data, need 2D Lists/Arrays.
   - Can use mathematical operations
   - Can be indexed in the same way
2. - List is from basic python, Array is from numpy.
   - min(list) vs array.min()
   - addition of list just combine them. addition of arrays add each element as long as the size are the same. Otherwise error.
3. - dictionary stores 2 sets of data, 1 as values and 1 as keys. Typing keys will give you the values. eg. print(dictionary_name["Key"])

## Exercise 2 :  Index me

In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                        # Prints 'a1'
                        # Prints 'c3'
                        # Prints 'e5'
                        # Prints 'g7'
print(py_list[0:9:2])   # Prints 'i9'


['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [6]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper() 
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper() 

print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [11]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1, 99, 62, 86, 43, 42, 60, 59, 1, 1, 35, 83, 47, 34, 28, 68, 23, 22, 92, 1, 79, 1, 29, 94, 72, 46, 47, 1, 74, 32, 20, 8, 37, 35, 1, 89, 29, 86, 19, 43, 61]
np_numbers=np.array(numbers)
print(np_numbers == 1)
print(sum(np_numbers == 1))

[False False  True False False  True False False False  True False False
 False False False False False  True  True False False False False False
 False False False False  True False  True False False False False False
  True False False False False False False  True False False False False
 False False]
9
