<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
# x = py_list  # OR
x = np_array

In [4]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

![](indexandslice1d.png)

### 1.2 Subsetting by masking (Arrays only)

In [5]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [6]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [13]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [11]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [15]:
py_list_2d[3]        # What is at position 4 (index 3)?

[4, 'D']

In [16]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [17]:
py_list_2d[3][1]

'D'

In [32]:
py_list_2d[3,1]

TypeError: list indices must be integers or slices, not tuple

In [21]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [22]:
py_list_2d[:3][0]

[1, 'A']

In [23]:
py_list_2d[:3][2][1]

'C'

In [26]:
py_list_2d[::2][2][1]

'E'

In [27]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [28]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [29]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U11')

In [30]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [31]:
np_array_2d[3][0]

'4'

In [33]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [34]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [36]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [35]:
np_array_2d[:3][0]

array(['1', 'A'], dtype='<U11')

In [37]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

In [41]:
np_array_2d[:]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

### 1.5 Growing lists

In [42]:
x=[1]*10
x               # I am lazy to type print()
                # Let Jupyter do the hard work.

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [43]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [44]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [45]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [46]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [50]:
x=[1]
x.append([2,3,4])
x

[1, [2, 3, 4]]

In [56]:
x = [1]
npx = np.array(x)
npx.append(2)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

## 2 Some loose ends

### 2.1 Tuples

In [57]:
a=(1, 2, 3)     # Define tuple

In [58]:
print(a[0])    # Access data

1


In [59]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

In [62]:
print(a[0] == [1])
print(a[0] == 1)

False
True


### 2.2 Be VERY careful when copying

In [63]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [64]:
y

[1, 2, 3]

In [65]:
y += [4]

In [66]:
x

[1, 2, 3, 4]

In [67]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [69]:
y += [4]

In [70]:
print(y)
print(x)

[1, 2, 3, 4]
[1, 2, 3]


## Exercise 1 :  Total recall?

|Term|Brief Description|
|:---|:----------------|
|Subsetting|selecting a subset of elements from the list/array|
|Indexing|choosing a certain element from the list/array|
|Slicing|choosing a range of element from the list/array|
|Masking|a way to subset arrays **only** which shows all elements that fulfill the criteria defined by me|

## Exercise 2 :  Show me the ‘odd’ letters

In [105]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[:,0]
x = np_array_2d[:,0]
y = (x.astype(int)) % 2
y == 1
odd = y == 1
np_array_2d[odd,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')